[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]

[features]
# qsound=true
# debug=true
beta=true

[parse]
sourcefile="mikie.cpp"

[buttons]
core=2 # max number of buttons supported by the core
names=[
    { names="A,B" }
]

[rbf]
name="jtmikie"

[dipsw]
delete = [ "Unused", "Unknown" ]
# base = 16

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu" },
    { name="audiocpu" },
    { name="gfx1" }, # start=$GFX1_START
    { name="gfx2" }, # start=$GFX2_START
    { name="proms"          },
]

order = [
    "maincpu", "audiocpu", "gfx1", "gfx2", "proms"
]


