[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]

[features]
# debug=true
beta=true

[parse]
sourcefile="hyperspt.cpp"

[buttons]
core=2 # max number of buttons supported by the core
names=[
    { names="Low gear,High gear" }
]

[rbf]
name="jtroadf"

[dipsw]
delete = [ "Unused", "Unknown" ]
# base = 16

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu" },
    { name="audiocpu" },
    { name="gfx2", width=16, no_offset=true, Sort_even=true, start=$SCR_START },
    { name="gfx1", width=16, no_offset=true, start=$OBJ_START },
    { name="vlm", reverse=true, start=$PCM_START },
    { name="proms", start=$PROM_START            },
]

order = [
    "maincpu", "audiocpu", "gfx2", "gfx1", "vlm", "proms"
]


