[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]

[features]
# debug=true
nvram=$JTFRAME_IOCTL_RD

[parse]
sourcefile="hyperspt.cpp"

[buttons]
core=3 # max number of buttons supported by the core
names=[
    { machine="roadf", names="Low gear,High gear" },
    { machine="hyperspt", names="Left button, Centre button, Right button" }
]

[rbf]
name="jtroadf"

[dipsw]
delete = [ "Unused", "Unknown" ]
bitcnt = 19
extra = [
    { machine="roadf", name="Flip", bits="16", Options="Off,On" }
]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu" },
    { name="audiocpu" },
    { name="gfx2", width=16, no_offset=true, Sort_even=true, start=$SCR_START },
    { machine="roadf", name="gfx1", width=16, no_offset=true, start=$OBJ_START },
    { machine="hyperspt", name="gfx1", width=16, no_offset=true, start=$OBJ_START, Name_sort=["c14","c18","c13","c17","c12","c16","c11","c15"] },
    { name="vlm", start=$PCM_START },
    { name="proms", start=$PROM_START            },
]

order = [
    "maincpu", "audiocpu", "gfx2", "gfx1", "vlm", "proms"
]

blanks = [
    { machine="hyperspt", region="gfx2", offset=0x4000, len=0x4000 }
]

