[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]

[features]
# debug=true

[parse]
sourcefile="rocnrope.cpp"
skip.bootlegs=true

[buttons]
core=2 # max number of buttons supported by the core
names=[{ names="Rope,Flash" }]

[rbf]
name="jtroc"

[dipsw]
delete = [ "Unused", "Unknown" ]
bitcnt = 23

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", no_offset=true },
    { name="timeplt_audio:tpsound", start=$SND_START },
    { name="gfx2", width=16, no_offset=true, Sort_even=true, start=$SCR_START },
    { name="gfx1", width=16, no_offset=true, start=$OBJ_START, sort_even=true },
    { name="proms", start=$PROM_START, name_sort=["b16_prom.bin","rocnrope.pr3","a17_prom.bin"], no_offset=true },
    { name="pal_cpuvidbd", skip=true },
    { name="pals_daughterbd", skip=true }
]

order = [
    "maincpu", "timeplt_audio:tpsound", "gfx2", "gfx1",  "proms"
]

# MAME applies this patch: fixes a bad dump?
patches = [
    { setname="rocnrope", offset=0x103d, value="BA" },
    { setname="ropeman", offset=0x103d, value="BA" }
]
