[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]

[features]
# qsound=true
# debug=true
beta=true

[parse]
sourcefile="sbasketb.cpp"

[buttons]
core=3 # max number of buttons supported by the core
names=[
    { names="Bounce,Throw,Pass" }
]

[rbf]
name="jtsbaskt"

[dipsw]
delete = [ "Unused", "Unknown" ]
# base = 16

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", reverse=true },
    { name="audiocpu" },
    { name="gfx1", reverse=true }, # start=$GFX1_START
    { name="gfx2" }, # start=$GFX2_START
    { name="vlm", reverse=true },
    { name="proms"          },
]

order = [
    "maincpu", "audiocpu", "gfx1", "gfx2", "vlm", "proms"
]


