[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]
platform="jtyiear"

[features]
# qsound=true
# debug=true

[parse]
sourcefile="yiear.cpp"

[buttons]
core=2 # max number of buttons supported by the core
names=[
    { names="Punch,Kick" }
]

[rbf]
name="jtyiear"

[dipsw]
delete = [ "Unused", "Unknown" ]
# base = 16

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", reverse=true },
    { name="gfx1", width=16, no_offset=true }, # start=$GFX1_START
    { name="gfx2", width=16, no_offset=true, Sort_even=true }, # start=$GFX2_START
    { name="vlm", reverse=true },
    { name="proms"          },
]

order = [
    "maincpu", "gfx1", "gfx2", "vlm", "proms"
]


